### ISSUE TITLE
Change Dryad conditions of access

### ISSUE THREAD

**Issue by candicecz** [NIAID-Data-Ecosystem/nde-crawlers#101]
Dryad has some datasets that have `conditionsOfAccess` as `public` . [API data](https://api-staging.data.niaid.nih.gov/v1/query?&q=conditionsOfAccess:public&facets=includedInDataCatalog.name&fields=conditionsOfAccess)

`conditionsOfAccess` should be an enum of either Closed, Embargoed, Restricted, or Open.

Could you change it to "Open"?

Thanks!

**Comment by jal347** [comment]
fixed and rerunning it rn
