### ISSUE TITLE
[Metadata Improvement]: Generate Benchmark measurementTechniques data for standardization

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#128]
### Issue Name

Generate Benchmark measurementTechniques data for standardization

### Issue Description

To readily benchmark measurementTechnique standardization approaches, it would be good to have a dataset of terms as a benchmark.

Aside from manually mapping existing terms, this benchmark could be generated with a few approaches:
- [x] Method 1: Programmatic generation of terms for standardization
    * Identifying mappings between the measurementTechnique ontologies ([see related issue](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/127))
    * Creating a list of terms that exist in more than one ontology
      * Note, the ontology IDs for each term should be saved/stored somewhere for QC after running T2T
    * Adding in a few sample terms from ontologies that did not get represented by the terms in the previous list
    * Manipulating terms in the list to alter capitalization, hyphenation, or pluralization
    * Add dummy stopwords like “administration”, “collection”, “analysis”, “study” to random subset of list
- [x] Method 2: Use ChatGPT to generate the terms
    * An example prompt can be found at: https://github.com/gtsueng/openai_topic_classification/blob/covid/prompt6.txt
    * For a variety of results, a small sample of records from the following repositories (25 per repository) should be run:
      * ClinEpiDB (Clinical techniques)
      * VDJ Server
      * OMICS DI
      * Zenodo
- [x] Method 3: Generate benchmark from existing measurementTechniques
    * Some repositories have more standardized values for measurementTechniques
    * For these repositories, generate a frequency table of the measurementTechnique values and map them manually. Then inspect how well the standardization and extraction processes work. These repositories include:
      - [x] NCBI GEO
      - [x] REFRAMEDB

### Issue Discussion

This issue is expected to be discussed only in the context of the results of the measurementTechnique standardization

### Please select the type of metadata improvement

- [X] Standardization (normalizing free text to an ontology)
- [ ] Augmentation (adding values for metadata fields missing values)
- [ ] Clean up (addressing redundancy or messy metadata)
- [ ] Structure (changing the structuring of the metadata to support front end UI features)

### Related WBS task

https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/13

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

### Request status check list

- [X] This metadata improvement has yet to be discussed between NIAID, Scripps, Leidos
- [ ] This metadata improvement does not need to be discussed between NIAID, Scripps, Leidos
- [ ] This metadata improvement has been discussed/reported between NIAID, Scripps, Leidos
- [ ] This metadata improvement has been implemented locally to generate data for review
- [ ] This metadata improvement has been implemented on Dev
- [ ] This metadata improvement has been implemented on Dev and the results have been reviewed and approved for staging
- [ ] This metadata improvement has been implemented on Staging
- [ ] This page/documentation/change has been approved for Production
- [ ] This page/documentation/change has been implemented on Production

**Comment by ZubairQazi** [comment]
Dumped into this spreadsheet:
https://docs.google.com/spreadsheets/d/1lG4hS-PQJ_IRxCc02W3Oz2OFMdYDMURRPbpm3Jg2kk0/edit#gid=1135725680

**Comment by gtsueng** [comment]
Great! Thanks @ZubairQazi that was useful for a sanity check. After the improvements, I think we can use this info, please take all the GPT predictions and generate a frequency table.

**Comment by gtsueng** [comment]
@DylanWelzel Once you figure out how to get and parse the mapping from NCBO BioPortal, you can use that to generate test data (Method 1) for evaluating your measurementTechnique standardization approach.

**Comment by gtsueng** [comment]
T2T evaluation results: https://docs.google.com/spreadsheets/d/1A0CR48cbAPiAhH4QKRXOJCAaY_bkNEysLjdM5Ofqzy0/edit?gid=165507656#gid=165507656

**Comment by gtsueng** [comment]
I am marking this issue as `pending close out` and will close it after a week if there are no additional concerns.
