### ISSUE TITLE
De-duplicate / combine records between NCBI GEO + OmicsDI

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-crawlers#43]
OmicsDI harvests all the records from GEO, but with less metadata.  Combine relevant metadata and de-duplicate the records.  See also #40 

### Related WBS task
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/14

**Comment by gtsueng** [comment]
It looks like the following fields can be used to match records between OMICS-DI and GEO:
* name (title of dataset)
* citation.pmid
* author.name

Merging will be challenging as there is metadata unique to each.

For example, https://data.niaid.nih.gov/resources?id=OMICSDI_PRJNA775608 and https://data.niaid.nih.gov/resources?id=GEO_GSE186705 appear to be duplicate entries. However:
* The GEO version appears to have better values for:
  * species
  * description
* While the OMICS-DI version has a value for measurementTechnique which is not the GEO record

A sampling/survey should be performed to determine the extent and consistency of these differences. The description for GEO datasets coming from OMICS-DI appear to have the 'name' field mirrored for 'description'; hence, 'description' will likely always be better from GEO.

**Comment by gtsueng** [comment]
Initially, it appeared that GEO has better values for:
* species
* description
An evaluation of duplicates identified via matching names and citation.pmids indicate that GEO is NOT better than OMICS-DI for the description field and that this field should be normalized between the GEO and OMICS-DI parsers before the duplicates are merged.

In the following example of duplicates, we can see that the [NDE's record of the dataset as ingested from OMICS-DI](https://data.niaid.nih.gov/resources?id=OMICSDI_GSE5833) has a longer description than the [NDE's record of the dataset as ingested from GEO](https://data.niaid.nih.gov/resources?id=GEO_GSE5833). Further investigation reveals that the [OMICS-DI record for this dataset](https://www.omicsdi.org/dataset/geo/GSE5833) does not match NDE's record of the dataset. Furthermore, the NDE's record as ingested from OMICS-DI actually aggregates additional information which is available in [GEO's record of the dataset](https://data.niaid.nih.gov/resources?id=GEO_GSE5833) but not [NDE's ingestion of the record from GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE5833)

NDE's ingestion of the record from OMICS-DI
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/d9191410-192b-450d-8e9d-20bff1b99c1d)

OMICS-DI's version of the record
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/21994d38-6289-4d7d-b627-5475045cf2e2)

NDE's ingestion of the record from GEO
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/6ab34e24-d2e8-4ca5-bb90-e8a321036e5c)

GEO's version of the record
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/a9fa83fc-6a33-4a57-b6ed-37f03ef72c9a)

Resolving the differences between the handling of the 'description' field should enable us to merge the duplicates without worrying about which repository should override for conflicting 'descriptions'. Differences in the parsing may affect other metadata fields; however, it may not be as necessary to resolve those as they are expected to be unique between the repositories and should theoretically 'merge' without overwriting.

**Comment by gtsueng** [comment]
Per discussions the week of 2023.10.16, the GEO parser will be improved to have better descriptions. Both OMICS-DI and GEO will have the source names removed from the `_id` prefix to enable merging of GEO datasets with OMICS-DI datasets (which apparently augment each dataset with a `variableMeasured` value

**Comment by gtsueng** [comment]
Implemented, but awaiting build completion in staging

**Comment by gtsueng** [comment]
Available on staging

**Comment by gtsueng** [comment]
The number of duplicate records that are estimated to have been de-duplicated/merged are:
69782 between NCBI GEO and OMICS DI
290 between LINCS and OMICS DI

**Comment by hartwickma** [comment]
Thank you for the presentation on this issue from Scripps on 7 January 2024. The outcome from this approach sound promising. OK to move to production.

Please note: NIAID recognizes and is appreciative of the level of detail and would suggest that requests for NIAID feedback be focused more on outcome and impact rather than methods and approaches.

**Comment by gtsueng** [comment]
This has been moved to Production on 2024.01.29. The status of the issue has been changed to `pending close out` and will close after 1 week, if there are no further concerns about this issue.
