### ISSUE TITLE
Potentially add funding info to OmicsDI

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-crawlers#49]
Via publications, link OmicsDI datasets to funding information.

Major question to consider: is a `publication` associated with an OmicsDI record only primary data generation or also secondary analyses of those datasets?  Does it matter when connecting to grant numbers?

**Comment by gtsueng** [comment]
The PMID helper for funding, infectiousAgent, species, and healthCondition should now be in use for all the crawlers.
