### ISSUE TITLE
Filter out deleted Zenodo entries

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-crawlers#85]
If possible, it'd be good to filter out the deleted Zenodo entries:
https://data-staging.niaid.nih.gov/portal/search/?q=ZENODO_4724093&from=1
https://data-staging.niaid.nih.gov/portal/search/?q=ZENODO_3953758&from=1
etc.

**Comment by gtsueng** [comment]
This appears to have been addressed when the duplicate issues in Zenodo were addressed
