### ISSUE TITLE
[SOURCE] Add LINCS Data Portal metadata

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-crawlers#87]
Harvest metadata from the [LINCS Data Portal](https://lincsportal.ccs.miami.edu/datasets/). It looks like their [API](https://lincsportal.ccs.miami.edu/dcic/api/fetchdata?limit=1000&searchTerm=*&skip=0&sort=datasetname+asc) should provide most of the metadata. 

Notes:
* They have a version 2.0, which seems to be the same metadata, but would be good to confirm
* That version has some API documentation associated with it, but i couldn't find anything on the `fetchdata` endpoint.

**Comment by flaneuse** [comment]
Also: there's another version of this data too via another project: https://maayanlab.cloud/sigcom-lincs/#/MetadataSearch/Datasets?query={%22skip%22:0,%22limit%22:10,%22search%22:[]}

It seems like they lack more metadata fields, BUT they have a few more datasets.  🤷‍♀️

**Comment by gtsueng** [comment]
BD2K LINCS is available in the NIAID Data Ecosystem, and the duplication issue between BD2K-LINCS and OMICS-DI have been addressed
